update sfe
mcclowes/docs-test pull request #14
Opened 2023-01-28 16:51 UTC by jmyorston

updated sfe links, fixed product sidebar for sfe

2023-01-30 09:51 UTC, d-laing requested changes
Looks great!

2023-01-30 09:51 UTC, d-laing commented on docs/sync-for-expenses/configandcategorize.md
> +1). Each Foreign Exchange currency has its own bank account
Please use full stops after numbers in lists. See the specification for GitHub Flavored Markdown:

https://github.github.com/gfm/#ordered-list-marker

2023-01-30 09:51 UTC, d-laing commented on docs/sync-for-expenses/configandcategorize.md
> +There are two ways to handle transactions in a foreign currency
```suggestion
There are two ways to handle transactions in a foreign currency:
```

2023-01-30 09:51 UTC, d-laing commented on docs/sync-for-expenses/configandcategorize.md
> +2). Each transaction is converted back to the currency of the bank account
```suggestion
2). Each transaction is converted back to the currency of the bank account.
```

2023-01-30 09:51 UTC, d-laing commented on docs/sync-for-expenses/configandcategorize.md
> +Today Sync for Expenses only supports option 2.
```suggestion
Sync for Expenses currently supports option 2 only.
```

2023-01-30 09:51 UTC, d-laing commented on docs/sync-for-expenses/sync-process/syncing-expenses.md
> +Sync's are independent of creating datasets, so you can continue to create new datasets whilst a sync is ongoing.
```suggestion
Syncs are independent of creating datasets, so you can continue to create new datasets while a sync is ongoing.
```

2023-01-30 14:00 UTC, d-laing requested changes
Fixed the numbering. Please ensure all numbered lists use the same format, thanks.

2023-01-30 14:00 UTC, d-laing commented on docs/sync-for-expenses/configandcategorize.md
> +1). Each Foreign Exchange currency has its own bank account
```suggestion
1. Each Foreign Exchange currency has its own bank account
```

2023-01-30 14:00 UTC, d-laing commented on docs/sync-for-expenses/configandcategorize.md
> +2). Each transaction is converted back to the currency of the bank account.
```suggestion
2. Each transaction is converted back to the currency of the bank account.
```

2023-02-01 18:43 UTC, mcclowes approved these changes

2023-02-01 18:44 UTC, merged